/* eslint-disable @next/next/inline-script-id */
/* eslint-disable react/jsx-no-comment-textnodes */
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Script>
        {`
           let toggleBtn = document.querySelector("#navbar-toggle");
           let collapse = document.querySelector("#navbar-collapse");
           
           toggleBtn.onclick = () => {
             collapse.classList.toggle("hidden");
             collapse.classList.toggle("block");
           };           
          `}
      </Script>
    </html>
  )
}
